export const INGREDIENTE_COLORES = {
  'Arroz Blanco': '#F5F0E8', 'Arroz Integral': '#C8A87A', 'Quinua': '#D4B896', 'Mix Asiático': '#E8D4B0',
  'Zuquini': '#7DC67E', 'Pepino': '#A8D87A', 'Tomate Cherry': '#E8584A', 'Zanahoria': '#F08030',
  'Repollo Encurtido': '#C870A8', 'Cebolla Encurtida': '#E0A0C8', 'Berenjena': '#6040A0', 'Brócoli': '#40A040',
  'Maíz': '#FFD040', 'Mango': '#F0A030', 'Manzana': '#E87080', 'Queso parmesano': '#F0E0A0',
  'Aguacate': '#80C060', 'Jalapeños': '#40A040', 'Lenteja Crocante': '#C87820', 'Garbanzo Crocante': '#D4A050',
  'Pechuga de Pollo': '#E0A060', 'Huevo Cocido': '#F8D870', 'Tofu': '#F0E8D0', 'Carne': '#8B4020',
  'Lomo de Cerdo': '#A05030', 'Máximo (Doble)': '#E0A060',
  'Pesto Natural': '#3DB870', 'Yogurt de Casa': '#F8F8F8', 'Vino Natural': '#8040A0',
  'Fuego Picante': '#E04020', 'Dulce Balance': '#F8D040',
};

export const CARTA = [
  {
    id: 'tierra',
    nombre: 'ORIGEN TIERRA',
    proteina: 'Salmón',
    precio: 44900,
    imagen: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400&h=400',
    badge: { texto: 'Premium', color: '#C9A227', bg: '#F0E8D8' },
    ingredientes: ['Arroz blanco', 'Repollo', 'Aguacate', 'Pepino', 'Mango', 'Garbanzo', 'Salmón', 'Semillas de calabaza'],
    tag: 'Mariscos',
    dietary: ['Gluten-Free', 'High-Protein'],
  },
  {
    id: 'fuego',
    nombre: 'ORIGEN FUEGO',
    proteina: 'Camarón',
    precio: 39900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1780285300/ORIGEN_CAMARON_errnem.webp',
    badge: { texto: 'Spicy', color: '#C84020', bg: '#F8EDED' },
    ingredientes: ['Mix asiático', 'Berenjena', 'Aguacate', 'Cherry', 'Lenteja', 'Arándanos', 'Camarón', 'Almendras'],
    tag: 'Mariscos',
    dietary: ['Raw', 'Gluten-Free'],
  },
  {
    id: 'agua',
    nombre: 'ORIGEN AGUA',
    proteina: 'Atún',
    precio: 42900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1780285300/ORIGEN_ATUN_qvtarw.webp',
    badge: { texto: 'Gluten-Free', color: '#315B7E', bg: '#F0F5F8' },
    ingredientes: ['Mix asiático', 'Pepino', 'Aguacate', 'Queso parmesano', 'Manzana', 'Arándanos', 'Atún', 'Semillas de girasol'],
    tag: 'Mariscos',
    dietary: ['Gluten-Free', 'High-Protein'],
  },
  {
    id: 'raiz',
    nombre: 'ORIGEN RAÍZ',
    proteina: 'Atún en Yogurt',
    precio: 40900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1780285300/ORIGEN_RAIZ_ATUN_puhjsi.webp',
    badge: { texto: 'Premium', color: '#C9A227', bg: '#F0E8D8' },
    ingredientes: ['Arroz blanco', 'Brócoli', 'Aguacate', 'Zanahoria', 'Champiñones', 'Mango', 'Atún en yogurt', 'Almendras'],
    tag: 'Mariscos',
    dietary: ['High-Protein'],
  },
  {
    id: 'aire',
    nombre: 'ORIGEN AIRE',
    proteina: 'Pechuga de Pollo',
    precio: 26900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1781820485/5_ORIGEN_AIRE_jlcw2w.webp',
    badge: { texto: 'Favorito', color: '#1EAD61', bg: '#E8F5E8' },
    ingredientes: ['Arroz integral', 'Pepino', 'Zuquini', 'Manzana', 'Arándanos', 'Garbanzo', 'Pechuga de pollo', 'Semillas de calabaza'],
    tag: 'Proteína Animal',
    dietary: ['Gluten-Free', 'High-Protein'],
  },
  {
    id: 'brasa',
    nombre: 'ORIGEN BRASA',
    proteina: 'Carne',
    precio: 28900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1781820466/7_ORIGEN_BRASA_k3bjhr.webp',
    badge: { texto: 'Grill', color: '#2D3A2D', bg: '#F5F5F5' },
    ingredientes: ['Arroz blanco', 'Zanahoria', 'Zuquini', 'Cherry', 'Champiñones', 'Parmesano', 'Carne', 'Semillas de calabaza'],
    tag: 'Proteína Animal',
    dietary: ['High-Protein'],
  },
  {
    id: 'dulce',
    nombre: 'ORIGEN DULCE',
    proteina: 'Lomo Miel Mostaza',
    precio: 28900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1780285300/ORIGEN_LOMO_zqrfqh.webp',
    badge: { texto: 'Especial', color: '#D47A40', bg: '#F8F0E8' },
    ingredientes: ['Arroz blanco', 'Pepino', 'Zanahoria', 'Repollo encurtido', 'Maíz', 'Aguacate', 'Lomo de cerdo', 'Almendras'],
    tag: 'Proteína Animal',
    dietary: ['Gluten-Free'],
  },
  {
    id: 'cosecha',
    nombre: 'ORIGEN COSECHA',
    proteina: 'Lomo de Cerdo',
    precio: 27900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1780285300/ORIGEN_COSECHA_LOMO_cfbzy9.webp',
    badge: { texto: 'Temporada', color: '#1EAD61', bg: '#E8F5E8' },
    ingredientes: ['Quinua', 'Berenjena', 'Pepino', 'Repollo encurtido', 'Garbanzo', 'Mango', 'Lomo de cerdo', 'Semillas de calabaza'],
    tag: 'Proteína Animal',
    dietary: ['Gluten-Free'],
  },
  {
    id: 'paraiso',
    nombre: 'ORIGEN PARAÍSO',
    proteina: 'Pechuga',
    precio: 26900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1781728305/WhatsApp_Image_2026-06-16_at_22.10.09_wni0gx.jpg',
    badge: { texto: 'Frutal', color: '#D47A40', bg: '#F8F0E8' },
    ingredientes: ['Cogollo', 'Zanahoria', 'Mango', 'Manzana', 'Aguacate', 'Kiwi', 'Fresa', 'Pechuga', 'Maní', 'Salsa'],
    tag: 'Proteína Animal',
    dietary: ['Raw'],
  },
  {
    id: 'natural',
    nombre: 'ORIGEN NATURAL',
    proteina: 'Huevo Cocido',
    precio: 19900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1780285300/ORIGEN_HUEVO_pgzav3.webp',
    badge: { texto: 'Plant-Based', color: '#1EAD61', bg: '#E8F5E8' },
    ingredientes: ['Mix asiático', 'Cherry', 'Zanahoria', 'Aguacate', 'Arándanos', 'Champiñones', 'Huevos cocidos', 'Semillas de girasol'],
    tag: 'Vegetariano',
    dietary: ['Gluten-Free', 'Vegetariano'],
  },
  {
    id: 'vital',
    nombre: 'ORIGEN VITAL',
    proteina: 'Tofu',
    precio: 22900,
    imagen: 'https://res.cloudinary.com/dfj0ckm10/image/upload/q_auto/f_auto/v1781824629/ORIGEN_TOFU_fuukpp.png',
    badge: { texto: '100% Plant', color: '#1EAD61', bg: '#E8F5E8' },
    ingredientes: ['Quinua', 'Zuquini', 'Zanahoria', 'Repollo encurtido', 'Mango', 'Champiñones', 'Tofu', 'Semillas de girasol'],
    tag: 'Vegetariano',
    dietary: ['Vegetariano', 'Gluten-Free'],
  },
];

export const BEBIDAS = [
  { id: 'limonada-natural', nombre: 'Limonada Natural', precio: 5900, desc: 'Limonada fresca preparada al instante con limón real.', emoji: '🍋' },
  { id: 'jugo-agua', nombre: 'Jugo Natural en Agua', precio: 5900, desc: 'Jugos naturales del día preparados con agua fresca.', emoji: '🧃' },
  { id: 'jugo-leche', nombre: 'Jugo Natural en Leche', precio: 6900, desc: 'Jugos naturales del día preparados con leche entera.', emoji: '🥛' },
  { id: 'agua-mineral', nombre: 'Agua Mineral', precio: 5900, desc: 'Agua mineral natural sin gas, pura y refrescante.', emoji: '💧' },
  { id: 'agua-gas', nombre: 'Agua con Gas', precio: 5900, desc: 'Agua mineral con gas natural, ligera y refrescante.', emoji: '💦' },
  { id: 'te-hatsu', nombre: 'Té Hatsu', precio: 7900, desc: 'Té natural Hatsu artesanal en diferentes sabores.', emoji: '🍵' },
  { id: 'soda-hatsu', nombre: 'Soda Hatsu', precio: 6900, desc: 'Soda refrescante Hatsu, burbujas naturales de caña.', emoji: '🥤' },
];
